theme: jekyll-theme-architect
show_downloads: 
url: "https://dashflow.io"
title: dashflow
description: Easily create database driven email dashboards and configured via simple json file.
github:
  zip_url: https://github.com/maximoguerrero/dashflow/archive/master.zip