theme: jekyll-theme-slate
show_downloads: true
title: Dash Flow - Database Driven Email Dashboards
description: Easily create email dashboard and configured via simple json file.
github:
  zip_url: https://github.com/maximoguerrero/dashflow/archive/master.zip